/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cc;

public class App {
    
    public static String project = "D:\\HHome\\GoogleDrive\\myjob\\resources\\project";
    
    public static String base(String prjId){
        return project+"\\"+prjId;
    }
    
}
